# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Keshav Katwe | Web Designer & Developer
description: > # this means to ignore newlines until "baseurl:"
  Keshav is a web designer and developer with One year and Ten month experience.
  
email: keshav.katwe@gmail.com
firstname: keshav
lastname: katwe
mobile: +91 953 865 0838
dob: 18 Feb, 1991

  
skype: keshav.katwe  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://keshavkatwe.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js]